

install:
	mkdir -p /usr/local/lib/lua/5.4/	# just for ensuring that the dest dir exists
	mkdir -p /usr/local/share/lua/5.4/	# just for ensuring that the dest dir exists
	#mv liblibc.so /usr/local/lib/lua/5.4/
	cp heapq.lua /usr/local/share/lua/5.4/
